### PR TITLE
Merge Sprint1 into master

### PR DESCRIPTION
**Pull request by angelavu**
Finish HW-1 Source Control by merging Sprint1 into master.

Features from Sprint1:
- Added timer component @benjaminvinicky
- Added counter component @mjosephwarren 
- Added phrase generator component @jamesp21 
- Added even or odd number checker component @angelavu

### CODE REVIEW

**Comment by angelavu** [comment]
Looks great!

**Comment by mjosephwarren** [comment]
Looks good. Nice job team!

**Comment by jamesp21** [comment]
looks good

**Comment by benjaminvinicky** [comment]
I approve these changes!

-Benjamin Vinicky does not claim liability for any damage, loss of property, or otherwise negative effects that these changes may introduce.

**Pull request merged**
